services:
  mongo-cli:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://jocham-user:lbjKMTf8d3sQ8q2M@s-fc0a667a-6ce3-4893-89a5-77e4661a3e2c-0.mongodb.eu01.onstackit.cloud:27017,s-fc0a667a-6ce3-4893-89a5-77e4661a3e2c-1.mongodb.eu01.onstackit.cloud:27017,s-fc0a667a-6ce3-4893-89a5-77e4661a3e2c-2.mongodb.eu01.onstackit.cloud:27017/stackit?authSource=stackit&tls=true&authMechanism=SCRAM-SHA-256
      - MONGO_DATABASE=test_db
      - MIGRATIONS_PATH=/app/migrations
      - MIGRATIONS_COLLECTION=schema_migrations
      - MONGO_TIMEOUT=30
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      mongo-db:
        condition: service_healthy
    # Default command is --help, but can be overridden
    command: ["--help"]
    networks:
      - cli-network

  mongo-mcp:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    environment:
      - MONGO_URL=mongodb://jocham-user:lbjKMTf8d3sQ8q2M@s-fc0a667a-6ce3-4893-89a5-77e4661a3e2c-0.mongodb.eu01.onstackit.cloud:27017,s-fc0a667a-6ce3-4893-89a5-77e4661a3e2c-1.mongodb.eu01.onstackit.cloud:27017,s-fc0a667a-6ce3-4893-89a5-77e4661a3e2c-2.mongodb.eu01.onstackit.cloud:27017/stackit?authSource=stackit&tls=true&authMechanism=SCRAM-SHA-256
      - MONGO_DATABASE=stackit
      - MIGRATIONS_PATH=/app/migrations
      - MIGRATIONS_COLLECTION=schema_migrations
      - MONGO_TIMEOUT=30
    ports:
      - "8080:8080" # Expose a port if your MCP server needs it
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      mongo-db:
        condition: service_healthy
    networks:
      - cli-network

  mongo-db:
    image: mongo:8.0
    command: [
      "--bind_ip_all",
      "--port", "27017"
    ]
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=test_db
    healthcheck:
      test: |
        echo 'db.runCommand("ping").ok' | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 10s
      start_interval: 1s
      retries: 30
    volumes:
      - mongo_data:/data/db
    networks:
      - cli-network

volumes:
  mongo_data:

networks:
  cli-network:
    driver: bridge
