services:
  cli:
    build:
      context: ..
      dockerfile: docker/Dockerfile.local
    environment:
      - MONGO_URL=mongodb://admin:password@mongo:27017/?authSource=admin&replicaSet=rs0
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=password
      - MONGO_AUTH_SOURCE=admin
      - MONGO_DATABASE=cli_integration
      - MIGRATIONS_COLLECTION=schema_migrations_cli_integration
      - MONGO_SSL_ENABLED=false
      - MONGO_TIMEOUT=30
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - cli-network

  mongo:
    image: mongo:8.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=cli_integration
    healthcheck:
      test: |
        mongosh --quiet --eval '
          try {
            rs.status();
          } catch (err) {
            rs.initiate({
              _id: "rs0",
              members: [{ _id: 0, host: "mongo:27017" }]
            });
          }
        '
      interval: 5s
      timeout: 30s
      start_period: 10s
      start_interval: 1s
      retries: 30
    ports:
      - "${INTEGRATION_MONGO_PORT:-37017}:27017"
    networks:
      - cli-network

networks:
  cli-network:
    driver: bridge
